### ISSUE TITLE
Is project abandoned?

### ISSUE THREAD

**Issue by Meister1593** [owenthereal/upterm#95]
There doesnt seem to be much of an activity in repo and serious issues (like #93) are not resolved.

Even though servers for sharing are still active, they might not be if they are not funded for long enough.

So, naturally, there comes a question... is project dead?

**Comment by owenthereal** [comment]
Nope, the community server (`uptermd.upterm.dev`) is down due to too much load. The server is served at the best efforts and I pay for the infra myself out of my pocket. If you're looking for a more reliable service, I would recommend hosting your own: https://github.com/owenthereal/upterm#deploy-uptermd.
